export const AIRLINE_NAMES: Record<string, string> = {
  BA: "British Airways",
  VS: "Virgin Atlantic",
  UA: "United Airlines",
  AA: "American Airlines",
  DL: "Delta Air Lines",
  AF: "Air France",
  KL: "KLM Royal Dutch Airlines",
  LH: "Lufthansa",
  EK: "Emirates",
  QR: "Qatar Airways",
  SQ: "Singapore Airlines",
  CX: "Cathay Pacific",
  NH: "ANA",
  JL: "Japan Airlines",
  AC: "Air Canada",
  AS: "Alaska Airlines",
  B6: "JetBlue",
  WN: "Southwest Airlines",
  TK: "Turkish Airlines",
  IB: "Iberia",
  AY: "Finnair",
  SK: "SAS",
  EY: "Etihad Airways",
  AV: "Avianca",
  TP: "TAP Air Portugal",
  LX: "Swiss International",
  OS: "Austrian Airlines",
  SN: "Brussels Airlines",
};

export const AIRLINE_COLORS: Record<string, string> = {
  BA: "#075AAA",
  VS: "#E61E2A",
  UA: "#002244",
  AA: "#B6322D",
  DL: "#003366",
  AF: "#002157",
  KL: "#00A1DE",
  LH: "#05164D",
  EK: "#D71921",
  QR: "#5C0632",
  SQ: "#F5A623",
  CX: "#006564",
  NH: "#13448F",
  JL: "#C8102E",
  AC: "#D92228",
  AS: "#01426A",
  B6: "#003876",
  WN: "#304CB2",
  TK: "#C7222A",
  IB: "#D71A21",
  AY: "#0B1560",
  EY: "#BD8B13",
  AV: "#E31837",
  TP: "#00956B",
  LX: "#E2001A",
};
