import type { FlightResult } from "./FlightResultCard";

export const mockFlights: FlightResult[] = [
  {
    id: "1",
    airline: "British Airways",
    airlineCode: "BA",
    airlineColor: "#075AAA",
    flightNumber: "BA 178",
    departureTime: "7:30 PM",
    arrivalTime: "7:45 AM+1",
    departureAirport: "JFK",
    arrivalAirport: "LHR",
    duration: "7h 15m",
    stops: 0,
    cabin: "Business",
    aircraft: "Boeing 787-9 Dreamliner",
    bestPoints: 50000,
    bestProgram: "British Airways Avios",
    cashTax: 238,
    badge: "best-deal",
    transferOptions: [
      {
        program: "British Airways Avios",
        points: 50000,
        transferFrom: "Chase Ultimate Rewards",
        transferRatio: "1:1",
        badge: "best",
      },
      {
        program: "American Airlines AAdvantage",
        points: 57500,
        transferFrom: "Citi ThankYou",
        transferRatio: "1:1",
      },
      {
        program: "Alaska Airlines Mileage Plan",
        points: 60000,
      },
      {
        program: "Qantas Frequent Flyer",
        points: 62000,
        transferFrom: "Amex Membership Rewards",
        transferRatio: "1:1",
      },
    ],
  },
  {
    id: "2",
    airline: "Virgin Atlantic",
    airlineCode: "VS",
    airlineColor: "#B80024",
    flightNumber: "VS 4",
    departureTime: "9:55 PM",
    arrivalTime: "10:15 AM+1",
    departureAirport: "JFK",
    arrivalAirport: "LHR",
    duration: "7h 20m",
    stops: 0,
    cabin: "Business",
    aircraft: "Airbus A350-1000",
    bestPoints: 47500,
    bestProgram: "Virgin Atlantic Flying Club",
    cashTax: 214,
    badge: "lowest-points",
    transferOptions: [
      {
        program: "Virgin Atlantic Flying Club",
        points: 47500,
        transferFrom: "Chase Ultimate Rewards",
        transferRatio: "1:1",
        badge: "best",
      },
      {
        program: "Delta SkyMiles",
        points: 85000,
      },
      {
        program: "Air France-KLM Flying Blue",
        points: 72000,
        transferFrom: "Amex Membership Rewards",
        transferRatio: "1:1",
      },
    ],
  },
  {
    id: "3",
    airline: "United Airlines",
    airlineCode: "UA",
    airlineColor: "#002244",
    flightNumber: "UA 14",
    departureTime: "10:30 PM",
    arrivalTime: "11:00 AM+1",
    departureAirport: "EWR",
    arrivalAirport: "LHR",
    duration: "7h 30m",
    stops: 0,
    cabin: "Business",
    aircraft: "Boeing 767-300ER",
    bestPoints: 60000,
    bestProgram: "United MileagePlus",
    cashTax: 56,
    transferOptions: [
      {
        program: "United MileagePlus",
        points: 60000,
        transferFrom: "Chase Ultimate Rewards",
        transferRatio: "1:1",
        badge: "best",
      },
      {
        program: "Avianca LifeMiles",
        points: 63000,
        transferFrom: "Amex Membership Rewards",
        transferRatio: "1:1",
      },
      {
        program: "Turkish Airlines Miles&Smiles",
        points: 45000,
        transferFrom: "Citi ThankYou",
        transferRatio: "1:1",
        badge: "fastest",
      },
    ],
  },
  {
    id: "4",
    airline: "American Airlines",
    airlineCode: "AA",
    airlineColor: "#B6322D",
    flightNumber: "AA 100",
    departureTime: "7:00 PM",
    arrivalTime: "7:00 AM+1",
    departureAirport: "JFK",
    arrivalAirport: "LHR",
    duration: "7h 00m",
    stops: 0,
    cabin: "Business",
    aircraft: "Boeing 777-300ER",
    bestPoints: 57500,
    bestProgram: "AAdvantage",
    cashTax: 68,
    badge: "fastest",
    transferOptions: [
      {
        program: "American Airlines AAdvantage",
        points: 57500,
        transferFrom: "Citi ThankYou",
        transferRatio: "1:1",
        badge: "best",
      },
      {
        program: "British Airways Avios",
        points: 60000,
        transferFrom: "Chase Ultimate Rewards",
        transferRatio: "1:1",
      },
      {
        program: "Etihad Guest",
        points: 62200,
      },
    ],
  },
  {
    id: "5",
    airline: "Air France",
    airlineCode: "AF",
    airlineColor: "#002157",
    flightNumber: "AF 22 → AF 1680",
    departureTime: "5:15 PM",
    arrivalTime: "10:30 AM+1",
    departureAirport: "JFK",
    arrivalAirport: "LHR",
    duration: "11h 15m",
    stops: 1,
    stopCity: "CDG",
    cabin: "Business",
    aircraft: "Boeing 777-200ER",
    bestPoints: 42000,
    bestProgram: "Flying Blue",
    cashTax: 198,
    transferOptions: [
      {
        program: "Air France-KLM Flying Blue",
        points: 42000,
        transferFrom: "Amex Membership Rewards",
        transferRatio: "1:1",
        badge: "best",
      },
      {
        program: "Virgin Atlantic Flying Club",
        points: 50000,
        transferFrom: "Chase Ultimate Rewards",
        transferRatio: "1:1",
      },
    ],
  },
  {
    id: "6",
    airline: "Delta Air Lines",
    airlineCode: "DL",
    airlineColor: "#003366",
    flightNumber: "DL 1 → DL 9470",
    departureTime: "6:00 PM",
    arrivalTime: "11:50 AM+1",
    departureAirport: "JFK",
    arrivalAirport: "LHR",
    duration: "11h 50m",
    stops: 1,
    stopCity: "AMS",
    cabin: "Business",
    aircraft: "Airbus A330-900neo",
    bestPoints: 72000,
    bestProgram: "Delta SkyMiles",
    cashTax: 82,
    transferOptions: [
      {
        program: "Delta SkyMiles",
        points: 72000,
        transferFrom: "Amex Membership Rewards",
        transferRatio: "1:1",
      },
      {
        program: "Virgin Atlantic Flying Club",
        points: 50000,
        transferFrom: "Chase Ultimate Rewards",
        transferRatio: "1:1",
        badge: "best",
      },
      {
        program: "Air France-KLM Flying Blue",
        points: 54000,
        transferFrom: "Capital One Miles",
        transferRatio: "1:1",
      },
    ],
  },
];
