import type { CreditCard } from "./types";

/* ─────────────────────────────────────────────────────────────────────────────
   Credit Card Catalog
   Comprehensive database of popular travel & cashback credit cards.
   Data is accurate as of 2026 — update annualCredits / earningRates as needed.
───────────────────────────────────────────────────────────────────────────── */

export const CREDIT_CARDS: CreditCard[] = [

  /* ── American Express Platinum ────────────────────────────────────────── */
  {
    id: "amex-platinum",
    name: "American Express Platinum Card",
    shortName: "The Platinum Card®",
    issuer: "amex",
    network: "amex",
    cardType: "travel",
    annualFee: 695,
    rewardsProgram: "Membership Rewards",
    cpp: 2.0,
    gradient: "linear-gradient(145deg, #c0c8d0 0%, #d4dce4 18%, #e4ecf2 34%, #eef4f8 48%, #e6eef4 62%, #d0d8e0 78%, #bcc4cc 92%, #b4bcc4 100%)",
    chipColor: "#c8a832",
    textColor: "#1c2430",
    subColor: "rgba(28,36,48,0.55)",
    logoEl: "amex",
    earningRates: [
      { category: "Flights", multiplier: 5, note: "booked directly with airlines or via Amex Travel" },
      { category: "Hotels", multiplier: 5, note: "booked via Amex Travel, on first $500k/year" },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "$200 Uber Cash", value: 200, description: "$15/month + $20 in December, auto-loaded to Uber account" },
      { name: "$200 Airline Fee Credit", value: 200, description: "Incidental fees with one selected airline per calendar year" },
      { name: "$200 Hotel Credit", value: 200, description: "At Fine Hotels + Resorts or The Hotel Collection via Amex Travel" },
      { name: "$100 Saks Fifth Avenue Credit", value: 100, description: "$50 Jan–Jun, $50 Jul–Dec at Saks Fifth Avenue" },
      { name: "$189 CLEAR Plus Credit", value: 189, description: "Annual CLEAR Plus membership credit" },
      { name: "$240 Digital Entertainment Credit", value: 240, description: "$20/month at Disney+, Hulu, ESPN+, Peacock, NYT, or WSJ" },
      { name: "$155 Walmart+ Credit", value: 155, description: "Monthly Walmart+ membership credit ($12.95/month)" },
      { name: "$300 Equinox Credit", value: 300, description: "$25/month toward eligible Equinox membership" },
    ],
    transferPartners: [
      { programId: "delta", name: "Delta SkyMiles", ratio: "1:1", category: "airline" },
      { programId: "air-canada", name: "Air Canada Aeroplan", ratio: "1:1", category: "airline" },
      { programId: "ana", name: "ANA Mileage Club", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "singapore", name: "Singapore KrisFlyer", ratio: "1:1", category: "airline" },
      { programId: "cathay", name: "Cathay Pacific Asia Miles", ratio: "1:1", category: "airline" },
      { programId: "emirates", name: "Emirates Skywards", ratio: "1:1", category: "airline" },
      { programId: "etihad", name: "Etihad Guest", ratio: "1:1", category: "airline" },
      { programId: "iberia", name: "Iberia Plus", ratio: "1:1", category: "airline" },
      { programId: "jetblue", name: "JetBlue TrueBlue", ratio: "1:0.8", category: "airline" },
      { programId: "qantas", name: "Qantas Frequent Flyer", ratio: "1:1", category: "airline" },
      { programId: "turkish", name: "Turkish Miles&Smiles", ratio: "1:1", category: "airline" },
      { programId: "virginatlantic", name: "Virgin Atlantic Flying Club", ratio: "1:1", category: "airline" },
      { programId: "hilton", name: "Hilton Honors", ratio: "1:2", category: "hotel" },
      { programId: "marriott", name: "Marriott Bonvoy", ratio: "1:1", category: "hotel" },
      { programId: "choice", name: "Choice Privileges", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "$200 Uber Cash",
      "$200 Airline Credit",
      "$200 Hotel Credit",
      "$100 Saks Credit",
      "$189 CLEAR Credit",
      "Centurion Lounge",
      "Priority Pass",
      "Global Entry",
    ],
  },

  /* ── American Express Gold ─────────────────────────────────────────────── */
  {
    id: "amex-gold",
    name: "American Express Gold Card",
    shortName: "Amex Gold Card",
    issuer: "amex",
    network: "amex",
    cardType: "travel",
    annualFee: 325,
    rewardsProgram: "Membership Rewards",
    cpp: 2.0,
    gradient: "linear-gradient(145deg, #c8922a 0%, #d4a030 20%, #e8b840 40%, #d4a030 60%, #c08020 80%, #b87020 100%)",
    chipColor: "#8B6914",
    textColor: "#fff8e8",
    subColor: "rgba(255,248,232,0.6)",
    logoEl: "amex",
    earningRates: [
      { category: "Dining", multiplier: 4, note: "at restaurants worldwide including delivery" },
      { category: "Groceries", multiplier: 4, cap: 25000, note: "at US supermarkets, then 1x" },
      { category: "Flights", multiplier: 3, note: "booked directly with airlines or via Amex Travel" },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "$120 Dining Credit", value: 120, description: "$10/month at Grubhub, The Cheesecake Factory, Goldbelly, Wine.com, or Five Guys" },
      { name: "$120 Uber Cash", value: 120, description: "$10/month toward Uber rides or Uber Eats" },
      { name: "$100 Hotel Credit", value: 100, description: "At The Hotel Collection properties via Amex Travel (2-night minimum)" },
      { name: "$84 Dunkin' Credit", value: 84, description: "$7/month at Dunkin' in the US" },
      { name: "$100 Resy Credit", value: 100, description: "$50 semi-annual credit at Resy restaurants in the US" },
    ],
    transferPartners: [
      { programId: "delta", name: "Delta SkyMiles", ratio: "1:1", category: "airline" },
      { programId: "air-canada", name: "Air Canada Aeroplan", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "hilton", name: "Hilton Honors", ratio: "1:2", category: "hotel" },
      { programId: "marriott", name: "Marriott Bonvoy", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "4x Dining",
      "4x Groceries",
      "3x Flights",
      "$120 Dining Credit",
      "$120 Uber Cash",
      "No FX Fees",
    ],
  },

  /* ── Chase Sapphire Preferred ──────────────────────────────────────────── */
  {
    id: "chase-sapphire-preferred",
    name: "Chase Sapphire Preferred® Card",
    shortName: "Sapphire Preferred",
    issuer: "chase",
    network: "visa",
    cardType: "travel",
    annualFee: 95,
    rewardsProgram: "Ultimate Rewards",
    cpp: 2.0,
    gradient: "linear-gradient(145deg, #0a1e58 0%, #152f7a 18%, #1c3f9e 38%, #1a3a92 55%, #0f2568 75%, #07174a 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.6)",
    logoEl: "visa",
    earningRates: [
      { category: "Travel", multiplier: 5, note: "on Chase Travel℠ purchases" },
      { category: "Dining", multiplier: 3 },
      { category: "Online groceries", multiplier: 3, note: "excluding Target, Walmart, wholesale clubs" },
      { category: "Streaming", multiplier: 3 },
      { category: "Travel", multiplier: 2, note: "all other travel not booked through Chase" },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "$50 Hotel Credit", value: 50, description: "Annual $50 credit on hotel stays booked through Chase Travel" },
    ],
    transferPartners: [
      { programId: "united", name: "United MileagePlus", ratio: "1:1", category: "airline" },
      { programId: "southwest", name: "Southwest Rapid Rewards", ratio: "1:1", category: "airline" },
      { programId: "air-canada", name: "Air Canada Aeroplan", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "jetblue", name: "JetBlue TrueBlue", ratio: "1:1", category: "airline" },
      { programId: "singapore", name: "Singapore KrisFlyer", ratio: "1:1", category: "airline" },
      { programId: "iberia", name: "Iberia Plus", ratio: "1:1", category: "airline" },
      { programId: "emirates", name: "Emirates Skywards", ratio: "1:1", category: "airline" },
      { programId: "hyatt", name: "World of Hyatt", ratio: "1:1", category: "hotel" },
      { programId: "ihg", name: "IHG One Rewards", ratio: "1:1", category: "hotel" },
      { programId: "marriott", name: "Marriott Bonvoy", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "$50 Hotel Credit",
      "3x Dining",
      "3x Travel",
      "Trip Insurance",
      "No FX Fees",
      "Primary Car Rental",
    ],
  },

  /* ── Chase Sapphire Reserve ────────────────────────────────────────────── */
  {
    id: "chase-sapphire-reserve",
    name: "Chase Sapphire Reserve®",
    shortName: "Sapphire Reserve",
    issuer: "chase",
    network: "visa",
    cardType: "travel",
    annualFee: 550,
    rewardsProgram: "Ultimate Rewards",
    cpp: 2.0,
    gradient: "linear-gradient(145deg, #1a1a2e 0%, #16213e 30%, #0f3460 60%, #1a1a2e 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "visa",
    earningRates: [
      { category: "Travel", multiplier: 10, note: "on Chase Travel℠ (hotels & car rentals after $300 credit)" },
      { category: "Dining", multiplier: 10, note: "on Chase Dining℠ purchases" },
      { category: "Dining", multiplier: 3, note: "worldwide dining not via Chase" },
      { category: "Travel", multiplier: 3, note: "after $300 annual travel credit" },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "$300 Travel Credit", value: 300, description: "Automatic statement credit for travel purchases each account anniversary" },
      { name: "$500 Hotel Credit", value: 500, description: "$250 twice per year at The Edit hotel collection properties" },
    ],
    transferPartners: [
      { programId: "united", name: "United MileagePlus", ratio: "1:1", category: "airline" },
      { programId: "southwest", name: "Southwest Rapid Rewards", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "singapore", name: "Singapore KrisFlyer", ratio: "1:1", category: "airline" },
      { programId: "hyatt", name: "World of Hyatt", ratio: "1:1", category: "hotel" },
      { programId: "ihg", name: "IHG One Rewards", ratio: "1:1", category: "hotel" },
      { programId: "marriott", name: "Marriott Bonvoy", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "$300 Travel Credit",
      "3x Dining",
      "3x Travel",
      "Priority Pass",
      "Global Entry",
      "No FX Fees",
    ],
  },

  /* ── Chase Freedom Unlimited ───────────────────────────────────────────── */
  {
    id: "chase-freedom-unlimited",
    name: "Chase Freedom Unlimited®",
    shortName: "Freedom Unlimited",
    issuer: "chase",
    network: "visa",
    cardType: "cashback",
    annualFee: 0,
    rewardsProgram: "Ultimate Rewards",
    cpp: 1.0,
    gradient: "linear-gradient(145deg, #1a1a2e 0%, #2a2a4e 40%, #1a1a2e 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "visa",
    earningRates: [
      { category: "Travel", multiplier: 5, note: "booked through Chase Travel℠" },
      { category: "Dining", multiplier: 3 },
      { category: "Drugstores", multiplier: 3 },
      { category: "All purchases", multiplier: 1.5, note: "unlimited 1.5% cash back" },
    ],
    annualCredits: [],
    transferPartners: [],
    benefits: [
      "1.5% All Purchases",
      "3x Dining",
      "5x Chase Travel",
      "No Annual Fee",
      "0% Intro APR",
    ],
  },

  /* ── Citi Premier Card ─────────────────────────────────────────────────── */
  {
    id: "citi-premier",
    name: "Citi Premier® Card",
    shortName: "Citi Premier",
    issuer: "citi",
    network: "mastercard",
    cardType: "travel",
    annualFee: 95,
    rewardsProgram: "ThankYou Points",
    cpp: 1.7,
    gradient: "linear-gradient(145deg, #003d7a 0%, #0055a5 40%, #003d7a 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "mc",
    earningRates: [
      { category: "Hotels", multiplier: 3 },
      { category: "Air Travel", multiplier: 3 },
      { category: "Groceries", multiplier: 3 },
      { category: "Restaurants", multiplier: 3 },
      { category: "Gas Stations", multiplier: 3 },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "$100 Hotel Credit", value: 100, description: "Annual $100 off a single hotel stay of $500+ booked via thankyou.com" },
    ],
    transferPartners: [
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "turkish", name: "Turkish Miles&Smiles", ratio: "1:1", category: "airline" },
      { programId: "singapore", name: "Singapore KrisFlyer", ratio: "1:1", category: "airline" },
      { programId: "emirates", name: "Emirates Skywards", ratio: "1:1", category: "airline" },
      { programId: "jetblue", name: "JetBlue TrueBlue", ratio: "1:1", category: "airline" },
      { programId: "avianca", name: "Avianca LifeMiles", ratio: "1:1", category: "airline" },
      { programId: "choice", name: "Choice Privileges", ratio: "1:2", category: "hotel" },
      { programId: "wyndham", name: "Wyndham Rewards", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "3x Hotels",
      "3x Flights",
      "3x Dining",
      "3x Groceries",
      "$100 Hotel Credit",
      "No FX Fees",
    ],
  },

  /* ── Capital One Venture X ─────────────────────────────────────────────── */
  {
    id: "capital-one-venture-x",
    name: "Capital One Venture X Rewards Credit Card",
    shortName: "Venture X",
    issuer: "capital-one",
    network: "visa",
    cardType: "travel",
    annualFee: 395,
    rewardsProgram: "Capital One Miles",
    cpp: 1.85,
    gradient: "linear-gradient(145deg, #1a1a1a 0%, #2d2d2d 30%, #1a1a1a 70%, #0d0d0d 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "visa",
    earningRates: [
      { category: "Capital One Travel", multiplier: 10, note: "hotels and rental cars booked via Capital One Travel" },
      { category: "Capital One Travel", multiplier: 5, note: "flights booked via Capital One Travel" },
      { category: "All purchases", multiplier: 2 },
    ],
    annualCredits: [
      { name: "$300 Travel Credit", value: 300, description: "Annual statement credit for Capital One Travel bookings" },
      { name: "10,000 Miles Bonus", value: 100, description: "10,000 bonus miles every account anniversary (~$100 in travel value)" },
    ],
    transferPartners: [
      { programId: "air-canada", name: "Air Canada Aeroplan", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "avianca", name: "Avianca LifeMiles", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "cathay", name: "Cathay Pacific Asia Miles", ratio: "1:1", category: "airline" },
      { programId: "emirates", name: "Emirates Skywards", ratio: "1:1", category: "airline" },
      { programId: "singapore", name: "Singapore KrisFlyer", ratio: "1:1", category: "airline" },
      { programId: "turkish", name: "Turkish Miles&Smiles", ratio: "1:1", category: "airline" },
      { programId: "wyndham", name: "Wyndham Rewards", ratio: "1:1", category: "hotel" },
      { programId: "choice", name: "Choice Privileges", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "$300 Travel Credit",
      "2x All Purchases",
      "10x Hotels (C1 Travel)",
      "Priority Pass",
      "Global Entry",
      "No FX Fees",
    ],
  },

  /* ── Capital One Venture ───────────────────────────────────────────────── */
  {
    id: "capital-one-venture",
    name: "Capital One Venture Rewards Credit Card",
    shortName: "Capital One Venture",
    issuer: "capital-one",
    network: "visa",
    cardType: "travel",
    annualFee: 95,
    rewardsProgram: "Capital One Miles",
    cpp: 1.7,
    gradient: "linear-gradient(145deg, #c0392b 0%, #d44332 40%, #c0392b 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "visa",
    earningRates: [
      { category: "Hotels & Rental Cars", multiplier: 5, note: "booked via Capital One Travel" },
      { category: "All purchases", multiplier: 2 },
    ],
    annualCredits: [
      { name: "Global Entry / TSA PreCheck Credit", value: 100, description: "Up to $100 credit for Global Entry or TSA PreCheck application fee" },
    ],
    transferPartners: [
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "emirates", name: "Emirates Skywards", ratio: "1:1", category: "airline" },
      { programId: "turkish", name: "Turkish Miles&Smiles", ratio: "1:1", category: "airline" },
      { programId: "wyndham", name: "Wyndham Rewards", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "2x All Purchases",
      "5x Hotels (C1 Travel)",
      "Global Entry Credit",
      "No FX Fees",
    ],
  },

  /* ── Apple Card ────────────────────────────────────────────────────────── */
  {
    id: "apple-card",
    name: "Apple Card",
    shortName: "Apple Card",
    issuer: "apple",
    network: "mastercard",
    cardType: "cashback",
    annualFee: 0,
    rewardsProgram: "Daily Cash",
    cpp: 1.0,
    gradient: "linear-gradient(145deg, #f5f5f7 0%, #ffffff 25%, #eeeeef 55%, #e3e3e5 78%, #d8d8da 100%)",
    chipColor: "#a8a8a8",
    textColor: "#1d1d1f",
    subColor: "rgba(0,0,0,0.35)",
    logoEl: "mc",
    earningRates: [
      { category: "Apple Purchases", multiplier: 3, note: "Apple Store, App Store, Apple Services, Apple Pay at Apple" },
      { category: "Apple Pay", multiplier: 2, note: "everywhere Apple Pay is accepted" },
      { category: "All purchases", multiplier: 1, note: "physical card transactions" },
    ],
    annualCredits: [],
    transferPartners: [],
    benefits: [
      "3% on Apple",
      "2% Apple Pay",
      "1% All Else",
      "0% Financing",
      "No Fees Ever",
      "Daily Cash",
    ],
  },

  /* ── Citi Double Cash ──────────────────────────────────────────────────── */
  {
    id: "citi-double-cash",
    name: "Citi Double Cash® Card",
    shortName: "Citi Double Cash",
    issuer: "citi",
    network: "mastercard",
    cardType: "cashback",
    annualFee: 0,
    rewardsProgram: "ThankYou Points",
    cpp: 1.0,
    gradient: "linear-gradient(145deg, #2c5282 0%, #3a6fa8 40%, #2c5282 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "mc",
    earningRates: [
      { category: "All purchases", multiplier: 1, note: "1% when you buy" },
      { category: "All purchases (paid)", multiplier: 1, note: "additional 1% when you pay your bill = 2% total" },
    ],
    annualCredits: [],
    transferPartners: [
      { programId: "turkish", name: "Turkish Miles&Smiles", ratio: "1:1", category: "airline" },
      { programId: "jetblue", name: "JetBlue TrueBlue", ratio: "1:1", category: "airline" },
      { programId: "avianca", name: "Avianca LifeMiles", ratio: "1:1", category: "airline" },
    ],
    benefits: [
      "2% All Purchases",
      "No Annual Fee",
      "0% Intro APR",
      "No FX Fees",
    ],
  },

];
