import type { CreditCard } from "./types";

/* ─────────────────────────────────────────────────────────────────────────────
   Credit Card Catalog
   Comprehensive database of popular travel & cashback credit cards.
   Data is accurate as of 2026 — update annualCredits / earningRates as needed.
───────────────────────────────────────────────────────────────────────────── */

export const CREDIT_CARDS: CreditCard[] = [

  /* ── American Express Platinum ────────────────────────────────────────── */
  {
    id: "amex-platinum",
    name: "American Express Platinum Card",
    shortName: "The Platinum Card®",
    issuer: "amex",
    network: "amex",
    cardType: "travel",
    annualFee: 695,
    rewardsProgram: "Membership Rewards",
    cpp: 2.0,
    gradient: "linear-gradient(145deg, #c0c8d0 0%, #d4dce4 18%, #e4ecf2 34%, #eef4f8 48%, #e6eef4 62%, #d0d8e0 78%, #bcc4cc 92%, #b4bcc4 100%)",
    chipColor: "#c8a832",
    textColor: "#1c2430",
    subColor: "rgba(28,36,48,0.55)",
    logoEl: "amex",
    earningRates: [
      { category: "Flights", multiplier: 5, note: "booked directly with airlines or via Amex Travel" },
      { category: "Hotels", multiplier: 5, note: "booked via Amex Travel, on first $500k/year" },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "$200 Uber Cash", value: 200, description: "$15/month + $20 in December, auto-loaded to Uber account" },
      { name: "$200 Airline Fee Credit", value: 200, description: "Incidental fees with one selected airline per calendar year" },
      { name: "$200 Hotel Credit", value: 200, description: "At Fine Hotels + Resorts or The Hotel Collection via Amex Travel" },
      { name: "$100 Saks Fifth Avenue Credit", value: 100, description: "$50 Jan–Jun, $50 Jul–Dec at Saks Fifth Avenue" },
      { name: "$189 CLEAR Plus Credit", value: 189, description: "Annual CLEAR Plus membership credit" },
      { name: "$240 Digital Entertainment Credit", value: 240, description: "$20/month at Disney+, Hulu, ESPN+, Peacock, NYT, or WSJ" },
      { name: "$155 Walmart+ Credit", value: 155, description: "Monthly Walmart+ membership credit ($12.95/month)" },
      { name: "$300 Equinox Credit", value: 300, description: "$25/month toward eligible Equinox membership" },
    ],
    transferPartners: [
      { programId: "delta", name: "Delta SkyMiles", ratio: "1:1", category: "airline" },
      { programId: "air-canada", name: "Air Canada Aeroplan", ratio: "1:1", category: "airline" },
      { programId: "ana", name: "ANA Mileage Club", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "singapore", name: "Singapore KrisFlyer", ratio: "1:1", category: "airline" },
      { programId: "cathay", name: "Cathay Pacific Asia Miles", ratio: "1:1", category: "airline" },
      { programId: "emirates", name: "Emirates Skywards", ratio: "1:1", category: "airline" },
      { programId: "etihad", name: "Etihad Guest", ratio: "1:1", category: "airline" },
      { programId: "iberia", name: "Iberia Plus", ratio: "1:1", category: "airline" },
      { programId: "jetblue", name: "JetBlue TrueBlue", ratio: "1:0.8", category: "airline" },
      { programId: "qantas", name: "Qantas Frequent Flyer", ratio: "1:1", category: "airline" },
      { programId: "turkish", name: "Turkish Miles&Smiles", ratio: "1:1", category: "airline" },
      { programId: "virginatlantic", name: "Virgin Atlantic Flying Club", ratio: "1:1", category: "airline" },
      { programId: "hilton", name: "Hilton Honors", ratio: "1:2", category: "hotel" },
      { programId: "marriott", name: "Marriott Bonvoy", ratio: "1:1", category: "hotel" },
      { programId: "choice", name: "Choice Privileges", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "$200 Uber Cash",
      "$200 Airline Credit",
      "$200 Hotel Credit",
      "$100 Saks Credit",
      "$189 CLEAR Credit",
      "Centurion Lounge",
      "Priority Pass",
      "Global Entry",
    ],
  },

  /* ── American Express Gold ─────────────────────────────────────────────── */
  {
    id: "amex-gold",
    name: "American Express Gold Card",
    shortName: "Amex Gold Card",
    issuer: "amex",
    network: "amex",
    cardType: "travel",
    annualFee: 325,
    rewardsProgram: "Membership Rewards",
    cpp: 2.0,
    gradient: "linear-gradient(145deg, #c8922a 0%, #d4a030 20%, #e8b840 40%, #d4a030 60%, #c08020 80%, #b87020 100%)",
    chipColor: "#8B6914",
    textColor: "#fff8e8",
    subColor: "rgba(255,248,232,0.6)",
    logoEl: "amex",
    earningRates: [
      { category: "Dining", multiplier: 4, note: "at restaurants worldwide including delivery" },
      { category: "Groceries", multiplier: 4, cap: 25000, note: "at US supermarkets, then 1x" },
      { category: "Flights", multiplier: 3, note: "booked directly with airlines or via Amex Travel" },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "$120 Dining Credit", value: 120, description: "$10/month at Grubhub, The Cheesecake Factory, Goldbelly, Wine.com, or Five Guys" },
      { name: "$120 Uber Cash", value: 120, description: "$10/month toward Uber rides or Uber Eats" },
      { name: "$100 Hotel Credit", value: 100, description: "At The Hotel Collection properties via Amex Travel (2-night minimum)" },
      { name: "$84 Dunkin' Credit", value: 84, description: "$7/month at Dunkin' in the US" },
      { name: "$100 Resy Credit", value: 100, description: "$50 semi-annual credit at Resy restaurants in the US" },
    ],
    transferPartners: [
      { programId: "delta", name: "Delta SkyMiles", ratio: "1:1", category: "airline" },
      { programId: "air-canada", name: "Air Canada Aeroplan", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "hilton", name: "Hilton Honors", ratio: "1:2", category: "hotel" },
      { programId: "marriott", name: "Marriott Bonvoy", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "4x Dining",
      "4x Groceries",
      "3x Flights",
      "$120 Dining Credit",
      "$120 Uber Cash",
      "No FX Fees",
    ],
  },

  /* ── Chase Sapphire Preferred ──────────────────────────────────────────── */
  {
    id: "chase-sapphire-preferred",
    name: "Chase Sapphire Preferred® Card",
    shortName: "Sapphire Preferred",
    issuer: "chase",
    network: "visa",
    cardType: "travel",
    annualFee: 95,
    rewardsProgram: "Ultimate Rewards",
    cpp: 2.0,
    gradient: "linear-gradient(145deg, #0a1e58 0%, #152f7a 18%, #1c3f9e 38%, #1a3a92 55%, #0f2568 75%, #07174a 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.6)",
    logoEl: "visa",
    earningRates: [
      { category: "Travel", multiplier: 5, note: "on Chase Travel℠ purchases" },
      { category: "Dining", multiplier: 3 },
      { category: "Online groceries", multiplier: 3, note: "excluding Target, Walmart, wholesale clubs" },
      { category: "Streaming", multiplier: 3 },
      { category: "Travel", multiplier: 2, note: "all other travel not booked through Chase" },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "$50 Hotel Credit", value: 50, description: "Annual $50 credit on hotel stays booked through Chase Travel" },
    ],
    transferPartners: [
      { programId: "united", name: "United MileagePlus", ratio: "1:1", category: "airline" },
      { programId: "southwest", name: "Southwest Rapid Rewards", ratio: "1:1", category: "airline" },
      { programId: "air-canada", name: "Air Canada Aeroplan", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "jetblue", name: "JetBlue TrueBlue", ratio: "1:1", category: "airline" },
      { programId: "singapore", name: "Singapore KrisFlyer", ratio: "1:1", category: "airline" },
      { programId: "iberia", name: "Iberia Plus", ratio: "1:1", category: "airline" },
      { programId: "emirates", name: "Emirates Skywards", ratio: "1:1", category: "airline" },
      { programId: "hyatt", name: "World of Hyatt", ratio: "1:1", category: "hotel" },
      { programId: "ihg", name: "IHG One Rewards", ratio: "1:1", category: "hotel" },
      { programId: "marriott", name: "Marriott Bonvoy", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "$50 Hotel Credit",
      "3x Dining",
      "3x Travel",
      "Trip Insurance",
      "No FX Fees",
      "Primary Car Rental",
    ],
  },

  /* ── Chase Sapphire Reserve ────────────────────────────────────────────── */
  {
    id: "chase-sapphire-reserve",
    name: "Chase Sapphire Reserve®",
    shortName: "Sapphire Reserve",
    issuer: "chase",
    network: "visa",
    cardType: "travel",
    annualFee: 550,
    rewardsProgram: "Ultimate Rewards",
    cpp: 2.0,
    gradient: "linear-gradient(145deg, #1a1a2e 0%, #16213e 30%, #0f3460 60%, #1a1a2e 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "visa",
    earningRates: [
      { category: "Travel", multiplier: 10, note: "on Chase Travel℠ (hotels & car rentals after $300 credit)" },
      { category: "Dining", multiplier: 10, note: "on Chase Dining℠ purchases" },
      { category: "Dining", multiplier: 3, note: "worldwide dining not via Chase" },
      { category: "Travel", multiplier: 3, note: "after $300 annual travel credit" },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "$300 Travel Credit", value: 300, description: "Automatic statement credit for travel purchases each account anniversary" },
      { name: "$500 Hotel Credit", value: 500, description: "$250 twice per year at The Edit hotel collection properties" },
    ],
    transferPartners: [
      { programId: "united", name: "United MileagePlus", ratio: "1:1", category: "airline" },
      { programId: "southwest", name: "Southwest Rapid Rewards", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "singapore", name: "Singapore KrisFlyer", ratio: "1:1", category: "airline" },
      { programId: "hyatt", name: "World of Hyatt", ratio: "1:1", category: "hotel" },
      { programId: "ihg", name: "IHG One Rewards", ratio: "1:1", category: "hotel" },
      { programId: "marriott", name: "Marriott Bonvoy", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "$300 Travel Credit",
      "3x Dining",
      "3x Travel",
      "Priority Pass",
      "Global Entry",
      "No FX Fees",
    ],
  },

  /* ── Chase Freedom Unlimited ───────────────────────────────────────────── */
  {
    id: "chase-freedom-unlimited",
    name: "Chase Freedom Unlimited®",
    shortName: "Freedom Unlimited",
    issuer: "chase",
    network: "visa",
    cardType: "cashback",
    annualFee: 0,
    rewardsProgram: "Ultimate Rewards",
    cpp: 1.0,
    gradient: "linear-gradient(145deg, #1a1a2e 0%, #2a2a4e 40%, #1a1a2e 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "visa",
    earningRates: [
      { category: "Travel", multiplier: 5, note: "booked through Chase Travel℠" },
      { category: "Dining", multiplier: 3 },
      { category: "Drugstores", multiplier: 3 },
      { category: "All purchases", multiplier: 1.5, note: "unlimited 1.5% cash back" },
    ],
    annualCredits: [],
    transferPartners: [],
    benefits: [
      "1.5% All Purchases",
      "3x Dining",
      "5x Chase Travel",
      "No Annual Fee",
      "0% Intro APR",
    ],
  },

  /* ── Citi Premier Card ─────────────────────────────────────────────────── */
  {
    id: "citi-premier",
    name: "Citi Premier® Card",
    shortName: "Citi Premier",
    issuer: "citi",
    network: "mastercard",
    cardType: "travel",
    annualFee: 95,
    rewardsProgram: "ThankYou Points",
    cpp: 1.7,
    gradient: "linear-gradient(145deg, #003d7a 0%, #0055a5 40%, #003d7a 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "mc",
    earningRates: [
      { category: "Hotels", multiplier: 3 },
      { category: "Air Travel", multiplier: 3 },
      { category: "Groceries", multiplier: 3 },
      { category: "Restaurants", multiplier: 3 },
      { category: "Gas Stations", multiplier: 3 },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "$100 Hotel Credit", value: 100, description: "Annual $100 off a single hotel stay of $500+ booked via thankyou.com" },
    ],
    transferPartners: [
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "turkish", name: "Turkish Miles&Smiles", ratio: "1:1", category: "airline" },
      { programId: "singapore", name: "Singapore KrisFlyer", ratio: "1:1", category: "airline" },
      { programId: "emirates", name: "Emirates Skywards", ratio: "1:1", category: "airline" },
      { programId: "jetblue", name: "JetBlue TrueBlue", ratio: "1:1", category: "airline" },
      { programId: "avianca", name: "Avianca LifeMiles", ratio: "1:1", category: "airline" },
      { programId: "choice", name: "Choice Privileges", ratio: "1:2", category: "hotel" },
      { programId: "wyndham", name: "Wyndham Rewards", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "3x Hotels",
      "3x Flights",
      "3x Dining",
      "3x Groceries",
      "$100 Hotel Credit",
      "No FX Fees",
    ],
  },

  /* ── Capital One Venture X ─────────────────────────────────────────────── */
  {
    id: "capital-one-venture-x",
    name: "Capital One Venture X Rewards Credit Card",
    shortName: "Venture X",
    issuer: "capital-one",
    network: "visa",
    cardType: "travel",
    annualFee: 395,
    rewardsProgram: "Capital One Miles",
    cpp: 1.85,
    gradient: "linear-gradient(150deg, #081420 0%, #0d1f40 28%, #102850 55%, #0a1a36 80%, #05101c 100%)",
    chipColor: "#7a8ea0",
    textColor: "rgba(182,206,238,0.92)",
    subColor: "rgba(175,200,230,0.45)",
    logoEl: "visa",
    earningRates: [
      { category: "Capital One Travel", multiplier: 10, note: "hotels and rental cars booked via Capital One Travel" },
      { category: "Capital One Travel", multiplier: 5, note: "flights booked via Capital One Travel" },
      { category: "All purchases", multiplier: 2 },
    ],
    annualCredits: [
      { name: "$300 Travel Credit", value: 300, description: "Annual statement credit for Capital One Travel bookings" },
      { name: "10,000 Miles Bonus", value: 100, description: "10,000 bonus miles every account anniversary (~$100 in travel value)" },
    ],
    transferPartners: [
      { programId: "air-canada", name: "Air Canada Aeroplan", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "avianca", name: "Avianca LifeMiles", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "cathay", name: "Cathay Pacific Asia Miles", ratio: "1:1", category: "airline" },
      { programId: "emirates", name: "Emirates Skywards", ratio: "1:1", category: "airline" },
      { programId: "singapore", name: "Singapore KrisFlyer", ratio: "1:1", category: "airline" },
      { programId: "turkish", name: "Turkish Miles&Smiles", ratio: "1:1", category: "airline" },
      { programId: "wyndham", name: "Wyndham Rewards", ratio: "1:1", category: "hotel" },
      { programId: "choice", name: "Choice Privileges", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "$300 Travel Credit",
      "2x All Purchases",
      "10x Hotels (C1 Travel)",
      "Priority Pass",
      "Global Entry",
      "No FX Fees",
    ],
  },

  /* ── Capital One Venture ───────────────────────────────────────────────── */
  {
    id: "capital-one-venture",
    name: "Capital One Venture Rewards Credit Card",
    shortName: "Capital One Venture",
    issuer: "capital-one",
    network: "visa",
    cardType: "travel",
    annualFee: 95,
    rewardsProgram: "Capital One Miles",
    cpp: 1.7,
    gradient: "linear-gradient(145deg, #c0392b 0%, #d44332 40%, #c0392b 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "visa",
    earningRates: [
      { category: "Hotels & Rental Cars", multiplier: 5, note: "booked via Capital One Travel" },
      { category: "All purchases", multiplier: 2 },
    ],
    annualCredits: [
      { name: "Global Entry / TSA PreCheck Credit", value: 100, description: "Up to $100 credit for Global Entry or TSA PreCheck application fee" },
    ],
    transferPartners: [
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "emirates", name: "Emirates Skywards", ratio: "1:1", category: "airline" },
      { programId: "turkish", name: "Turkish Miles&Smiles", ratio: "1:1", category: "airline" },
      { programId: "wyndham", name: "Wyndham Rewards", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "2x All Purchases",
      "5x Hotels (C1 Travel)",
      "Global Entry Credit",
      "No FX Fees",
    ],
  },

  /* ── Apple Card ────────────────────────────────────────────────────────── */
  {
    id: "apple-card",
    name: "Apple Card",
    shortName: "Apple Card",
    issuer: "apple",
    network: "mastercard",
    cardType: "cashback",
    annualFee: 0,
    rewardsProgram: "Daily Cash",
    cpp: 1.0,
    gradient: "linear-gradient(145deg, #f5f5f7 0%, #ffffff 25%, #eeeeef 55%, #e3e3e5 78%, #d8d8da 100%)",
    chipColor: "#a8a8a8",
    textColor: "#1d1d1f",
    subColor: "rgba(0,0,0,0.35)",
    logoEl: "mc",
    earningRates: [
      { category: "Apple Purchases", multiplier: 3, note: "Apple Store, App Store, Apple Services, Apple Pay at Apple" },
      { category: "Apple Pay", multiplier: 2, note: "everywhere Apple Pay is accepted" },
      { category: "All purchases", multiplier: 1, note: "physical card transactions" },
    ],
    annualCredits: [],
    transferPartners: [],
    benefits: [
      "3% on Apple",
      "2% Apple Pay",
      "1% All Else",
      "0% Financing",
      "No Fees Ever",
      "Daily Cash",
    ],
  },

  /* ── Citi Double Cash ──────────────────────────────────────────────────── */
  {
    id: "citi-double-cash",
    name: "Citi Double Cash® Card",
    shortName: "Citi Double Cash",
    issuer: "citi",
    network: "mastercard",
    cardType: "cashback",
    annualFee: 0,
    rewardsProgram: "ThankYou Points",
    cpp: 1.0,
    gradient: "linear-gradient(145deg, #2c5282 0%, #3a6fa8 40%, #2c5282 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "mc",
    earningRates: [
      { category: "All purchases", multiplier: 1, note: "1% when you buy" },
      { category: "All purchases (paid)", multiplier: 1, note: "additional 1% when you pay your bill = 2% total" },
    ],
    annualCredits: [],
    transferPartners: [
      { programId: "turkish", name: "Turkish Miles&Smiles", ratio: "1:1", category: "airline" },
      { programId: "jetblue", name: "JetBlue TrueBlue", ratio: "1:1", category: "airline" },
      { programId: "avianca", name: "Avianca LifeMiles", ratio: "1:1", category: "airline" },
    ],
    benefits: [
      "2% All Purchases",
      "No Annual Fee",
      "0% Intro APR",
      "No FX Fees",
    ],
  },

  /* ── Bilt Mastercard ───────────────────────────────────────────────────── */
  {
    id: "bilt-mastercard",
    name: "Bilt Mastercard®",
    shortName: "Bilt Mastercard",
    issuer: "bilt",
    network: "mastercard",
    cardType: "rent",
    annualFee: 0,
    rewardsProgram: "Bilt Rewards",
    cpp: 1.5,
    gradient: "linear-gradient(145deg, #1a1a1a 0%, #2c2c2c 30%, #1a1a1a 70%, #0d0d0d 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "mc",
    earningRates: [
      { category: "Rent", multiplier: 1, note: "1x on rent with no transaction fees (up to 100,000 pts/year)" },
      { category: "Travel", multiplier: 3, note: "booked through Bilt Travel" },
      { category: "Dining", multiplier: 2 },
      { category: "All purchases", multiplier: 1, note: "must make 5 transactions per statement period" },
      { category: "Rent — Rent Day (1st of month)", multiplier: 6, note: "6x on dining, 3x on travel on the 1st of each month" },
    ],
    annualCredits: [
      { name: "No Rent Transaction Fee", value: 0, description: "Pay rent with no credit card processing fee — unique to Bilt" },
      { name: "Lyft Pink Membership", value: 199, description: "Complimentary Lyft Pink All Access membership (includes ride discounts)" },
      { name: "$5/month Bilt Dining Credit", value: 60, description: "$5/month credit at participating Bilt Dining network restaurants" },
    ],
    transferPartners: [
      { programId: "united", name: "United MileagePlus", ratio: "1:1", category: "airline" },
      { programId: "american", name: "American Airlines AAdvantage", ratio: "1:1", category: "airline" },
      { programId: "air-canada", name: "Air Canada Aeroplan", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "cathay", name: "Cathay Pacific Asia Miles", ratio: "1:1", category: "airline" },
      { programId: "emirates", name: "Emirates Skywards", ratio: "1:1", category: "airline" },
      { programId: "turkish", name: "Turkish Miles&Smiles", ratio: "1:1", category: "airline" },
      { programId: "virginatlantic", name: "Virgin Atlantic Flying Club", ratio: "1:1", category: "airline" },
      { programId: "alaska", name: "Alaska Mileage Plan", ratio: "1:1", category: "airline" },
      { programId: "hyatt", name: "World of Hyatt", ratio: "1:1", category: "hotel" },
      { programId: "ihg", name: "IHG One Rewards", ratio: "1:1", category: "hotel" },
      { programId: "marriott", name: "Marriott Bonvoy", ratio: "1:1", category: "hotel" },
      { programId: "hilton", name: "Hilton Honors", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "1x Rent (No Fee)",
      "3x Travel",
      "2x Dining",
      "6x Rent Day",
      "No Annual Fee",
      "Lyft Pink Membership",
    ],
  },

  /* ── Amex Business Platinum ────────────────────────────────────────────── */
  {
    id: "amex-business-platinum",
    name: "The Business Platinum Card® from American Express",
    shortName: "Amex Business Platinum",
    issuer: "amex",
    network: "amex",
    cardType: "business",
    annualFee: 695,
    rewardsProgram: "Membership Rewards",
    cpp: 2.0,
    gradient: "linear-gradient(145deg, #b8c0c8 0%, #ccd4dc 18%, #dce4ec 34%, #e8f0f6 48%, #dce4ec 62%, #ccd4dc 78%, #b4bcc4 92%, #aab2ba 100%)",
    chipColor: "#c8a832",
    textColor: "#1c2430",
    subColor: "rgba(28,36,48,0.55)",
    logoEl: "amex",
    earningRates: [
      { category: "Flights & Prepaid Hotels", multiplier: 5, note: "booked via Amex Travel" },
      { category: "Other purchases", multiplier: 1.5, note: "on purchases of $5,000+ per transaction" },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "$200 Airline Fee Credit", value: 200, description: "Incidental fees with one selected airline per year" },
      { name: "$189 CLEAR Plus Credit", value: 189, description: "Annual CLEAR Plus membership credit" },
      { name: "$200 Dell Credit", value: 200, description: "$100 Jan–Jun, $100 Jul–Dec on Dell.com" },
      { name: "$360 Indeed Credit", value: 360, description: "$90/quarter on Indeed hiring services" },
      { name: "$150 Adobe Credit", value: 150, description: "Annual credit on eligible Adobe purchases" },
      { name: "35% Airline Bonus", value: 0, description: "35% points back when using Pay with Points for first/business class via Amex Travel" },
    ],
    transferPartners: [
      { programId: "delta", name: "Delta SkyMiles", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "ana", name: "ANA Mileage Club", ratio: "1:1", category: "airline" },
      { programId: "singapore", name: "Singapore KrisFlyer", ratio: "1:1", category: "airline" },
      { programId: "emirates", name: "Emirates Skywards", ratio: "1:1", category: "airline" },
      { programId: "hilton", name: "Hilton Honors", ratio: "1:2", category: "hotel" },
      { programId: "marriott", name: "Marriott Bonvoy", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "5x Flights & Hotels",
      "1.5x on $5k+ Purchases",
      "$200 Airline Credit",
      "Centurion Lounge",
      "Priority Pass",
      "Global Entry",
      "35% Points Back",
    ],
  },

  /* ── Chase Ink Business Preferred ─────────────────────────────────────── */
  {
    id: "chase-ink-business-preferred",
    name: "Ink Business Preferred® Credit Card",
    shortName: "Ink Business Preferred",
    issuer: "chase",
    network: "visa",
    cardType: "business",
    annualFee: 95,
    rewardsProgram: "Ultimate Rewards",
    cpp: 2.0,
    gradient: "linear-gradient(145deg, #1b2a4a 0%, #253a60 30%, #1b2a4a 70%, #111d35 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "visa",
    earningRates: [
      { category: "Travel", multiplier: 3, cap: 150000, note: "first $150k combined spend per year" },
      { category: "Shipping", multiplier: 3, cap: 150000 },
      { category: "Advertising (social/search)", multiplier: 3, cap: 150000 },
      { category: "Internet, Cable & Phone", multiplier: 3, cap: 150000 },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [],
    transferPartners: [
      { programId: "united", name: "United MileagePlus", ratio: "1:1", category: "airline" },
      { programId: "southwest", name: "Southwest Rapid Rewards", ratio: "1:1", category: "airline" },
      { programId: "british-airways", name: "British Airways Avios", ratio: "1:1", category: "airline" },
      { programId: "air-france", name: "Air France Flying Blue", ratio: "1:1", category: "airline" },
      { programId: "singapore", name: "Singapore KrisFlyer", ratio: "1:1", category: "airline" },
      { programId: "hyatt", name: "World of Hyatt", ratio: "1:1", category: "hotel" },
      { programId: "ihg", name: "IHG One Rewards", ratio: "1:1", category: "hotel" },
      { programId: "marriott", name: "Marriott Bonvoy", ratio: "1:1", category: "hotel" },
    ],
    benefits: [
      "3x Travel",
      "3x Shipping",
      "3x Advertising",
      "25% Redemption Bonus",
      "Cell Phone Protection",
      "No FX Fees",
    ],
  },

  /* ── Discover it® Student Cash Back ────────────────────────────────────── */
  {
    id: "discover-it-student",
    name: "Discover it® Student Cash Back",
    shortName: "Discover it Student",
    issuer: "discover",
    network: "discover",
    cardType: "student",
    annualFee: 0,
    rewardsProgram: "Discover Cashback",
    cpp: 1.0,
    gradient: "linear-gradient(145deg, #e8541a 0%, #f06624 30%, #e8541a 70%, #c84010 100%)",
    chipColor: "#a8a8a8",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.6)",
    logoEl: "discover",
    earningRates: [
      { category: "Rotating quarterly categories", multiplier: 5, cap: 1500, note: "activate each quarter (e.g. gas, restaurants, Amazon, groceries)" },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "Cashback Match", value: 0, description: "Discover matches all cash back earned in your first year — effectively doubling it" },
      { name: "$20 Good Grade Reward", value: 20, description: "$20 statement credit each school year your GPA is 3.0 or higher (up to 5 years)" },
    ],
    transferPartners: [],
    benefits: [
      "5% Rotating Categories",
      "First Year Match",
      "No Annual Fee",
      "No FX Fees",
      "$20 Good Grade Reward",
      "Free FICO Score",
    ],
  },

  /* ── World of Hyatt Credit Card ────────────────────────────────────────── */
  {
    id: "hyatt-credit-card",
    name: "The World of Hyatt Credit Card",
    shortName: "World of Hyatt Card",
    issuer: "chase",
    network: "visa",
    cardType: "hotel",
    annualFee: 95,
    rewardsProgram: "World of Hyatt",
    cpp: 1.7,
    gradient: "linear-gradient(145deg, #1a1a2e 0%, #2a1a3e 30%, #1a0a2e 70%, #0d0018 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "visa",
    earningRates: [
      { category: "Hyatt Hotels", multiplier: 9, note: "4x base + 5x elite bonus (Discoverist status)" },
      { category: "Dining", multiplier: 2 },
      { category: "Local Transit & Commuting", multiplier: 2 },
      { category: "Fitness Clubs & Gym Memberships", multiplier: 2 },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "1 Free Night (Category 1–4)", value: 150, description: "Free night award at any Category 1–4 Hyatt property each account anniversary" },
      { name: "Discoverist Status", value: 0, description: "Automatic World of Hyatt Discoverist elite status while card is open" },
    ],
    transferPartners: [],
    benefits: [
      "9x at Hyatt",
      "2x Dining",
      "Free Night Annually",
      "Discoverist Status",
      "No FX Fees",
    ],
  },

  /* ── Delta SkyMiles® Gold American Express Card ────────────────────────── */
  {
    id: "delta-gold-amex",
    name: "Delta SkyMiles® Gold American Express Card",
    shortName: "Delta Gold Amex",
    issuer: "amex",
    network: "amex",
    cardType: "airline",
    annualFee: 150,
    rewardsProgram: "Delta SkyMiles",
    cpp: 1.1,
    gradient: "linear-gradient(145deg, #8b0000 0%, #a80000 25%, #c00000 50%, #a80000 75%, #8b0000 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "amex",
    earningRates: [
      { category: "Delta Purchases", multiplier: 2 },
      { category: "Restaurants", multiplier: 2 },
      { category: "U.S. Supermarkets", multiplier: 2 },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "First Checked Bag Free", value: 60, description: "Free first checked bag for you and up to 8 companions on Delta flights" },
      { name: "$200 Delta Flight Credit", value: 200, description: "$200 Delta flight credit after spending $10,000 in a year" },
    ],
    transferPartners: [],
    benefits: [
      "2x Delta Purchases",
      "2x Dining",
      "Free Checked Bag",
      "Priority Boarding",
      "20% In-Flight Savings",
    ],
  },

  /* ── United℠ Explorer Card ─────────────────────────────────────────────── */
  {
    id: "united-explorer",
    name: "United℠ Explorer Card",
    shortName: "United Explorer",
    issuer: "chase",
    network: "visa",
    cardType: "airline",
    annualFee: 95,
    rewardsProgram: "United MileagePlus",
    cpp: 1.2,
    gradient: "linear-gradient(145deg, #003580 0%, #0050b3 30%, #003580 70%, #002060 100%)",
    chipColor: "#c8a832",
    textColor: "#ffffff",
    subColor: "rgba(255,255,255,0.55)",
    logoEl: "visa",
    earningRates: [
      { category: "United Purchases", multiplier: 2 },
      { category: "Dining", multiplier: 2 },
      { category: "Hotel Stays", multiplier: 2 },
      { category: "All purchases", multiplier: 1 },
    ],
    annualCredits: [
      { name: "First Checked Bag Free", value: 140, description: "Free first checked bag for you and a companion on United flights" },
      { name: "2 United Club Passes", value: 118, description: "Two United Club one-time passes per year" },
      { name: "$100 Global Entry/TSA", value: 100, description: "Statement credit for Global Entry or TSA PreCheck application fee" },
    ],
    transferPartners: [],
    benefits: [
      "2x United Purchases",
      "2x Dining",
      "Free Checked Bag",
      "2 United Club Passes",
      "Global Entry Credit",
      "25% In-Flight Discount",
    ],
  },

];

